# Generated by Django 6.0.6 on 2026-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_address_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], default='CUSTOMER', max_length=20),
        ),
    ]
