services:

  db:
    image: postgres:15

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: madhubalabirla
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

volumes:
  postgres_data: